name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo ${{ github.ref_name }}
  
  test:
    #    needs: print-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./mesto-react
        run: npm install

      - name: Run tests
        working-directory: ./mesto-react
        run: npm run test