---
name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  print-version:
   runs-on: ubuntu-latest
   steps:
    - name: Print version
      run: echo ${{ github.ref_name }}
  test:
#    needs: print-version
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test
